### ISSUE TITLE
VMs cannot talk to each other within same host or across hosts

### ISSUE THREAD

**Issue by besanradwan** [rcbops/ansible-lxc-rpc#116]
Cannot ping from vm to vm on same tenant or even ping from vm to vm across tenants

**Comment by cloudnull** [comment]
I am not able to recreate this issue in the IAD3 lab. Please check your VXLAN network settings, kernel versions, and any application IP table rules.

**Comment by besanradwan** [comment]
The reason behind this problem was that the security group was not configured correctly even though the ports were open. It was in an error state. To solve it, a new security group was created with all ports open including UDP, TCP, and ICMP.
