### ISSUE TITLE
Slow Network Performance

### ISSUE THREAD

**Issue by besanradwan** [rcbops/ansible-lxc-rpc#131]
When Performance Team attempted to stress the Neutron VM Network, we found high latency. RPC network engineers found that packets were being routed through a 1Gb routing network/link. This is being worked on now by the BackBone engineers (BB team). We are waiting on a fix.

**Comment by andymcc** [comment]
@besanradwan does this relate to how the networks are configured from an ansible perspective or is it simply that the underlying networks are not configured correctly? I'm assuming the latter since Backbone are looking at it, in which case i'd like to close this bug out.

**Comment by jacobwagner** [comment]
Closing this as it is a hardware config issue
