### ISSUE TITLE
pw-token-gen script removes all commented lines

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/ansible-lxc-rpc#135]
When running scripts/pw-token-gen.py it removes all commented lines. this can cause issues as it will remove optional parameters that the user may wish to set after they generate their passwords, such as the maas_fqdn_extension variable.

**Comment by johnmarkschofield** [comment]
Agreed, it would be nice if we included the comments. However, PyYAML throws away comments at a deep level. I don't see a way to fix this in any simple way.

Brief discussion: https://stackoverflow.com/questions/7255885/save-dump-a-yaml-file-with-comments-in-pyyaml/7255983#7255983

PyYAML ticket with no movement in three years: http://pyyaml.org/ticket/114

**Comment by jacobwagner** [comment]
I guess we need to mark wont fix and close as this is not a 9.0 issue but a PyYAML issue that doesnt seem to be getting fixed any time soon.
