### ISSUE TITLE
when creating volume from image, cinder-volume can't find existing images

### ISSUE THREAD

**Issue by jcourtois** [rcbops/ansible-lxc-rpc#138]
When creating a volume from the ID of an existing image, the volume may end in an error state.  In the logs, cinder-volume reports an 'ImageCopyFailure' because it is unable to find an image with the given ID.

https://gist.github.com/jcourtois/2638c267ef7975f85d3b

Found in IAD lab 2.

**Comment by byronmccollum** [comment]
What is your Glance Image Backend (file or swift)? How many `infra` nodes do you have?

**Comment by byronmccollum** [comment]
Could be related to #37

**Comment by jcourtois** [comment]
CloudFiles backend with 3 infra nodes.

**Comment by cloudnull** [comment]
I have not been able to recreate this issue. Can you provide more details on the base image? where did the "existing image" come from? was it an image of a running instance? was the running instance deleted? Is the Image ID in the cloudfiles container?  Any details you can provide regarding this issue would be great.

**Comment by jcourtois** [comment]
Right, sorry about that lack of detail.  And I have to apologize, I was mistaken.  The lab in question was actually using the local filesystem as a backend.  Given that, it's probably related to #37.

The image in the logs was a cirros image (I think http://download.cirros-cloud.net/0.3.3/cirros-0.3.3-x86_64-disk.img) that had been downloaded to the filesystem then uploaded into glance using image-create and a reference to the file.

**Comment by cloudnull** [comment]
I'm closing this issue as it seems resolved when using a clustered storage system.  eg: swift, NFS, other. However please feel free to reopen this issue if it crops up again.
