### ISSUE TITLE
Keystone XmlBodyMiddleware Deprecated

### ISSUE THREAD

**Issue by mancdaz** [rcbops/ansible-lxc-rpc#140]
From `keystone.log`

```
2014-09-18 09:42:44.392 1822 WARNING keystone.openstack.common.versionutils [-] Deprecated: 
keystone.middleware.core.XmlBodyMiddleware is deprecated as of Icehouse in favor of support for 
"application/json" only and may be removed in Kilo.
```

Relevant lines in `keystone-paste.ini`

```
[filter:xml_body_v3]
paste.filter_factory=keystone.middleware:XmlBodyMiddlewareV3.factory

[filter:xml_body_v2]
paste.filter_factory=keystone.middleware:XmlBodyMiddlewareV2.factory

[filter:xml_body]
paste.filter_factory=keystone.middleware:XmlBodyMiddleware.factory
...

[pipeline:admin_api]
pipeline=sizelimit url_normalize build_auth_context token_auth admin_token_auth xml_body_v2 json_body ec2_extension s3_extension crud_extension admin_service

[pipeline:admin_version_api]
pipeline=sizelimit url_normalize xml_body admin_version_service

[pipeline:api_v3]
pipeline=sizelimit url_normalize build_auth_context token_auth admin_token_auth xml_body_v3 json_body ec2_extension_v3 s3_extension simple_cert_extension service_v3

[pipeline:public_version_api]
pipeline=sizelimit url_normalize xml_body public_version_service
```

Are there any reasons why we would not want to remove the xmlbodymiddleware support now?

**Comment by andymcc** [comment]
@mancdaz I think I'm getting theses (along with a bunch of other deprecated warnings) on icehouse stable so I'd say we should fix that up for both. In addition to keystone one above, (which I do get for icehouse stable) I get the following:

heat-engine: WARNING heat.common.config [-] The "instance_user" option in heat.conf is deprecated and will be removed in the Juno release.

glance-api: WARNING glance.store [-] Deprecated: glance.store.s3.Store not found in `known_store`. Stores need to be explicitly enabled in the configuration file.

cinder-api: Deprecated: Default quota for resource: volumes_lvm is set by the default quota flag: quota_volumes_lvm, it is now deprecated. Please use the the default quota class for default quota.

nova-compute: WARNING nova.virt.libvirt.vif [-] VIF driver "NeutronLinuxBridgeVIFDriver" is marked as deprecated and will be removed in the Juno release.

**Comment by mancdaz** [comment]
XML deprecation status varies between openstack projects.  We will be managing this via customer communications and advise regarding future deprecation/removal status.
