### ISSUE TITLE
Change default virt_type to kvm

### ISSUE THREAD

**Issue by claco** [rcbops/ansible-lxc-rpc#147]
The default virt_type is qemu, which if you forget to change it, causes all sorts of performance issues on real hardware. This was caught by the performance testing folks.

We have a few options:
- change the default to the most common setting for our real installations: kvm
- change the playbook to check for the best default value if it is not set in config (https://review.openstack.org/#/c/118093/)
- document that this needs to be changed during the installation process

**Comment by mancdaz** [comment]
already in stable/icehouse branch, after 9.0.0 tag
