### ISSUE TITLE
Missing Values In `metadata_agent.ini` Config

### ISSUE THREAD

**Issue by byronmccollum** [rcbops/ansible-lxc-rpc#16]
Some values (`nova_metadata_ip` and `metadata_proxy_shared_secret`) are not getting set / substituted. I looked at `vars/nova_all.yml` and everything seems correct. Not sure why the literal template strings aren't being parsed. 

```
[DEFAULT]
auth_url = http://172.29.236.4:5000/v2.0
auth_region = RegionOne
admin_tenant_name = service
admin_user = neutron
admin_password = herpderp
nova_metadata_ip = {{internal_vip_address}}
metadata_proxy_shared_secret = {{nova_metadata_proxy_secret}}
metadata_workers = 10
```

**Comment by andymcc** [comment]
This seems to be an ansible bug, we can fix this in the meantime by setting it to the actual variables.

**Comment by andymcc** [comment]
the only downside I can think of is that if we set the nova_groups var to something other than the "nova_metadata_proxy_secret" var, or "internal_lb_vip" address these 2 won't match, but we probably shouldn't be doing that.

**Comment by andymcc** [comment]
Checked through for any other occurrences of this bug - there aren't any so it should just be these 2, and we're talking with the Ansible guys re: fixing this upstream.

**Comment by cloudnull** [comment]
The fix has been merged. Please reopen if needed.
