### ISSUE TITLE
Upgrade to ansible 1.6.9

### ISSUE THREAD

**Issue by Apsu** [rcbops/ansible-lxc-rpc#184]
1.6.9 has a security fix for a vulnerability in 1.6.6, yet doesn't have a new bug which was introduced in the 1.7 series ( https://github.com/ansible/ansible/issues/8705 ) which breaks multi-forking delegation. This bug has been fixed in the devel branch but hasn't made it into an ansible release yet.

Confirmed 1.7.0, 1.7.1 and 1.7.2 are all broken.

**Comment by cloudnull** [comment]
this fix has been merged. in PR #148
