### ISSUE TITLE
heat template with SoftwareDeployment resource fails with AttributeError: _get

### ISSUE THREAD

**Issue by miguelgrinberg** [rcbops/ansible-lxc-rpc#190]
This has been fixed upstream, and the bug was recently merged to stable/icehouse, we just need to include it. Here is the bug report: https://bugs.launchpad.net/heat/+bug/1308770

**Comment by cloudnull** [comment]
@miguelgrinberg would you mind pulling the commit into your test cluster and giving it a go. It looks like if we change the heat sha on stable/icehouse to "830534149aea02a0435bf86565e91b4652032bcd" we should be good to go.

**Comment by cloudnull** [comment]
Is this still an issue with all the heat related changes that have been merged?

**Comment by miguelgrinberg** [comment]
Sorry, forgot to close this. Haven't seen this problem since we went to the newer heat. I have verified both Icehouse and Juno.
