### ISSUE TITLE
Heat configuration has several problems

### ISSUE THREAD

**Issue by miguelgrinberg** [rcbops/ansible-lxc-rpc#195]
RPC configures heat using the "trusts" authentication method, which requires some setup that is currently missing. The changes I had to make to get things to work are:
- Create a `heat` domain, using keystone v3 API. From the command line:
  
  ```
  openstack --os-identity-api-version=3 --os-token $TOKEN --os-url=http://172.24.240.10:5000/v3 domain create heat --description "Owns users and projects created by heat"
  ```
- Add the `admin` role to user `heat_domain_admin`. From cmd line:
  
  ```
  openstack --os-identity-api-version=3 --os-token $TOKEN --os-url=http://172.24.240.10:5000/v3 role add --user heat_domain_admin --domain <heat-domain-id> admin
  ```
- Set the `heat` domain for the `heat_domain_admin` user. Command:
  
  ```
  openstack --os-identity-api-version=3 --os-token $TOKEN --os-url=http://172.24.240.10:5000/v3 user set heat_domain_admin --domain heat
  ```
- Create the `heat_stack_user` role. Command:
  
  ```
  keystone role-create --name heat_stack_user
  ```

I haven't looked into incorporating these changes in the playbook yet. @mattt416 has done part of this work for Juno.

**Comment by cloudnull** [comment]
Is this manually configuring what the heat domain script is doing and or is this related to pr:
https://github.com/rcbops/ansible-lxc-rpc/pull/186 ?

**Comment by miguelgrinberg** [comment]
Yes, this is similar to what Matt's PR does, with the difference that my commands fix an existing RPC9 install instead of building things from scratch. Also note that the PR does not seem to create the heat_stack_user role (last item in my list), that needs to be added even for Juno.

**Comment by mattt416** [comment]
Doesn't look like `heat-keystone-setup-domain` is available in icehouse.  Assuming that it works on icehouse we could bundle it in ansible or alternatively use the openstack cli as documented by @miguelgrinberg.  If we go w/ the latter it may be worthwhile updating juno to use that method as well so that we're not doing things differently inbetween branches.

**Comment by mattt416** [comment]
@miguelgrinberg, we should probably try to use openstack cli first before bundling `heat-keystone-setup-domain`.  I will have a look at doing this tomorrow if you're not able to do today.

**Comment by miguelgrinberg** [comment]
I agree, openstack cli seems to be a better option, we can also find a way to fix the old broken configuration when the playbook runs a second time.

I need to investigate the configs a bit more. The code that parses the domain related entries changed a bit in Juno, hopefully we can find a set of variables that work for both. I'll let you know how far I get today.

**Comment by cloudnull** [comment]
I have merged the commit into stable/icehouse. I think we should keep this issue open until this work has also been done in Juno.
