### ISSUE TITLE
laying down example files on compute node fails

### ISSUE THREAD

**Issue by mancdaz** [rcbops/ansible-lxc-rpc#201]
```
TASK: [openstack_common | Laydown the example files] **************************
failed: [355166-node10] => {"failed": true, "rc": 258}
msg: cannot change to directory '/opt/neutron_master/etc/nova': path does not exist
```

Offending code is in https://github.com/rcbops/ansible-lxc-rpc/blob/master/rpc_deployment/roles/openstack_common/tasks/main.yml#L19-L24

This is possibly related to the change to make neutron use repo_packages: https://github.com/rcbops/ansible-lxc-rpc/pull/187

**Comment by cloudnull** [comment]
this should be resolved with the merge of PR: https://github.com/rcbops/ansible-lxc-rpc/pull/194. You may need to remove the "nova_*" directory in /opt and rerun but with the change it should be good to go.
