### ISSUE TITLE
Frozen repos - raxmon

### ISSUE THREAD

**Issue by mancdaz** [rcbops/ansible-lxc-rpc#21]
<a href="https://github.com/git-harry"><img src="https://avatars.githubusercontent.com/u/687171?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [git-harry](https://github.com/git-harry)**
_Friday Aug 08, 2014 at 09:41 GMT_
_Originally opened as https://github.com/rcbops/ansible-lxc-rpc-orig/issues/329_

---

https://github.com/rcbops/ansible-lxc-rpc/blob/master/rpc_deployment/roles/raxmon_agent_install/tasks/main.yml#L2-13

Are these tasks required?

**Comment by mancdaz** [comment]
<a href="https://github.com/mattt416"><img src="https://avatars.githubusercontent.com/u/16207?v=2" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mattt416](https://github.com/mattt416)**
_Monday Aug 11, 2014 at 09:40 GMT_

---

@aedan, can we get the rackspace monitoring agent package added to our frozen repo?

**Comment by mancdaz** [comment]
<a href="https://github.com/aedan"><img src="https://avatars.githubusercontent.com/u/1728973?v=2" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [aedan](https://github.com/aedan)**
_Thursday Aug 14, 2014 at 19:45 GMT_

---

@mattt416 Sure. I can do that.

**Comment by mancdaz** [comment]
<a href="https://github.com/aedan"><img src="https://avatars.githubusercontent.com/u/1728973?v=2" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [aedan](https://github.com/aedan)**
_Thursday Aug 14, 2014 at 22:24 GMT_

---

@mattt416 I have completed adding the monitoring agent to the repo.

**Comment by cloudnull** [comment]
Closed as the packages have been added.
