### ISSUE TITLE
Monitoring plays are noncomformant to the rest of the plays

### ISSUE THREAD

**Issue by cloudnull** [rcbops/ansible-lxc-rpc#255]
Presently monitoring does not use `vars/repo_packages`.  The files required to setup monitoring to use the proper files has been created however the _raxmon_agent_install_ role is not using any of the common roles to install packages or lay down base config. 

Purposed changes: 
- Remove package installation tasks from the _raxmon_agent_install_ role.
- Remove apt repo add tasks from the _raxmon_agent_install_ role.
- Remove git clone task from the _raxmon_agent_install_ role.
- Remove pip install task from the _raxmon_agent_install_ role.
- Remove **raxmon_agent_key** and **raxmon_agent_repos** from the `group_vars/hosts.yml`
- Convert the `raxmon-setup.yml` play to use `vars/repo_packages`.
- Include the _container_common_ role in the **raxmon-setup.yml** play to facilitate package installation and basic configuration duties.
- Consider changing **rackspace-monitoring** and **rackspace-monitoring-cli** installation to be done in separate tasks 
- Consider changing the installation process for **rackspace-monitoring** to use a source install from a given git sha. Presently these packages are being installed from the rackspace apt repo.

**Comment by mattt416** [comment]
Hi @cloudnull, would you mind giving this PR a once-over to ensure I'm on the right track?  I did not leave the git-related variables in the repo_packages file as rcbops/rpc-maas does not have a setup.py and cannot be 'installed' with pip.
