### ISSUE TITLE
stable/icehouse - chgrp failed: failed to look up groupt "root"

### ISSUE THREAD

**Issue by alextricity25** [rcbops/ansible-lxc-rpc#266]
I encountered this message when running the setup-common playbooks for the first time. As a note, I had the stable/icehouse branch checked out. 

TASK: [common | Drop rpc version file] ***************************************\* 
failed: [infra3] => {"failed": true, "gid": 0, "group": "root", "mode": "0644", "owner": "root", "path": "/etc/rpc-release", "size": 115, "state": "file", "uid": 0}
msg: chgrp failed: failed to look up group "root"

failed: [infra2] => {"failed": true, "gid": 0, "group": "root", "mode": "0644", "owner": "root", "path": "/etc/rpc-release", "size": 115, "state": "file", "uid": 0}
msg: chgrp failed: failed to look up group "root"

failed: [infra1] => {"failed": true, "gid": 0, "group": "root", "mode": "0644", "owner": "root", "path": "/etc/rpc-release", "size": 115, "state": "file", "uid": 0}
msg: chgrp failed: failed to look up group "root"

failed: [cinder1] => {"failed": true, "gid": 0, "group": "root", "mode": "0644", "owner": "root", "path": "/etc/rpc-release", "size": 115, "state": "file", "uid": 0}
msg: chgrp failed: failed to look up group "root"

failed: [logger1] => {"failed": true, "gid": 0, "group": "root", "mode": "0644", "owner": "root", "path": "/etc/rpc-release", "size": 115, "state": "file", "uid": 0}
failed: [compute1] => {"failed": true, "gid": 0, "group": "root", "mode": "0644", "owner": "root", "path": "/etc/rpc-release", "size": 115, "state": "file", "uid": 0}
msg: chgrp failed: failed to look up group "root"

msg: chgrp failed: failed to look up group "root"

When I ran it a second time, this specific task didn't fail, but I got the same message later on the "set apparmor profile for nova-compute" task.

**Comment by alextricity25** [comment]
Getting rid of these two lines fixed the issue. I was then able re-run the playbooks successfully. 
https://github.com/rcbops/ansible-lxc-rpc/blob/stable/icehouse/rpc_deployment/roles/lxc_common/tasks/lxc_host_setup.yml#L31-L32

**Comment by cloudnull** [comment]
So this issue is related to ansible adding whitespace to any resource block that uses ">" in it. This has been resolved in master though will need to be addressed for RPC 9.0.X

**Comment by alextricity25** [comment]
Tuned out to be a version issue on my part. I was running Ansible 1.6.10 with stable/icehouse when I should have been running 1.6.6.
