### ISSUE TITLE
Configuration generation is inconsistent

### ISSUE THREAD

**Issue by mancdaz** [rcbops/ansible-lxc-rpc#29]
<a href="https://github.com/andymcc"><img src="https://avatars.githubusercontent.com/u/1507326?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [andymcc](https://github.com/andymcc)**
_Friday Aug 22, 2014 at 15:41 GMT_
_Originally opened as https://github.com/rcbops/ansible-lxc-rpc-orig/issues/452_

---

At the moment we use a template generator for glance but not for nova (as an example).

We should probably make this consistent at some point.

**Comment by mancdaz** [comment]
<a href="https://github.com/cloudnull"><img src="https://avatars.githubusercontent.com/u/2066292?v=2" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cloudnull](https://github.com/cloudnull)**
_Friday Aug 22, 2014 at 15:58 GMT_

---

+1 I think we should get rid of the template generator we are using and simply use templates as they should be.  The idea of template generation was a good one, however it's not possible in all cases.

**Comment by cloudnull** [comment]
This was done in the pending PR #51.

**Comment by mattt416** [comment]
Hey @cloudnull, are you going to selectively bring in bits from your CDC branch or shall I manually merge the work you did for this fix specifically into master?

**Comment by cloudnull** [comment]
Hey  @mattt416  I've started to port over some of the bits but have not done this one. If you have cycles and want to do this by all means please do.
