### ISSUE TITLE
Glance requires an entry for snet endpoint even when not using swift for the image backend.

### ISSUE THREAD

**Issue by mancdaz** [rcbops/ansible-lxc-rpc#32]
<a href="https://github.com/cloudnull"><img src="https://avatars.githubusercontent.com/u/2066292?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cloudnull](https://github.com/cloudnull)**
_Monday Aug 25, 2014 at 20:43 GMT_
_Originally opened as https://github.com/rcbops/ansible-lxc-rpc-orig/issues/463_

---

When running a new installation the system attempts to laydown a host name for a service_net endpoint even when using a file backend. The desired outcome would be that all swift related options are optional and only parsed when set to a backend of swift. 

The task that is attempting to execute:
https://github.com/rcbops/ansible-lxc-rpc/blob/ead8d1d698aa2820f53a20c753f4f6db03e44b64/rpc_deployment/roles/glance_snet_override/tasks/main.yml

Valid Endpoints:
https://github.com/rcbops/ansible-lxc-rpc/blob/ead8d1d698aa2820f53a20c753f4f6db03e44b64/rpc_deployment/inventory/group_vars/glance_all.yml#L98-L116

Glance Options:
https://github.com/rcbops/ansible-lxc-rpc/blob/master/etc/rpc_deploy/user_variables.yml#L56-L65
- Running the code results with an error when snet is `true || false`
  glance_swift_enable_snet: false

``` bash
TASK: [glance_snet_override | Remove hosts entry if glance_swift_enable_snet is False] ***
fatal: [infra1_glance_container-dbd3a387] => One or more undefined variables: 'dict object' has no attribute 'SomeRegion'

FATAL: all hosts have already failed -- aborting
```

glance_swift_enable_snet: true

``` bash
TASK: [glance_snet_override | Add hosts entry if glance_swift_enable_snet is True] ***
fatal: [infra1_glance_container-dbd3a387] => One or more undefined variables: 'dict object' has no attribute 'SomeRegion'

FATAL: all hosts have already failed -- aborting
```

Related Issue: https://github.com/rcbops/ansible-lxc-rpc/issues/260

**Comment by mancdaz** [comment]
<a href="https://github.com/andymcc"><img src="https://avatars.githubusercontent.com/u/1507326?v=2" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [andymcc](https://github.com/andymcc)**
_Friday Aug 29, 2014 at 15:58 GMT_

---

In order to fix this we probably need to adjust the way glance is templated Related: #452 

Because we are using a "configuration generator" for glance it means we can't do an "if this is specified" section in the template configuration.

**Comment by andymcc** [comment]
@mattt416 's fix will address this bug, there is a more generic issue open regarding template generation so we can look into that in issue #29. 
Marking this pending merge.

**Comment by andymcc** [comment]
Closing this one out. We can deal with the conf generation in #29
