### ISSUE TITLE
Cinder is not using the storage_network if one is available

### ISSUE THREAD

**Issue by cloudnull** [rcbops/ansible-lxc-rpc#328]
Presently cinder will not explicitly use the storage network when one is available. If the user has set a storage network in the rpc_user_config.yml file then it should be safe to assume that iSCSI daemon will be forced to listen on and use the available storage network. 

**Here are the purposed changes that we should make to the cinder.conf file.**

``` ini
iscsi_iotype = {{ cinder_iscsi_iotype | default('fileio') }}
iscsi_ip_address = {{ storage_address | default(container_address) }}
iscsi_num_targets = {{ cinder_iscsi_num_targets | default('100') }}
iscsi_port = {{ cinder_iscsi_port | default('3260') }}
```

With these changes the iscsi_ip_address will be set the the devices storage_address from within inventory. Additionally we would be setting the iotype, number of available targets, and port.

This issue was identified by @byronmccollum

**Comment by byronmccollum** [comment]
Storage Network: `172.29.244.0/22`

```
root@rpc9ra-byronm-compute1:~# service open-iscsi status
Current active iSCSI sessions:
tcp: [1] 172.29.245.77:3260,1 iqn.2010-10.org.openstack:volume-ea791514-f5a8-4537-b408-ad57081797d5
```

Looks good on `stable/icehouse`...

**Comment by cloudnull** [comment]
in master and stable/icehouse. Closing.
