### ISSUE TITLE
[kibana] kibana is redirecting to internal lb elasticsearch vip when accessing from external vip, causing dashboard to fail

### ISSUE THREAD

**Issue by mancdaz** [rcbops/ansible-lxc-rpc#34]
<a href="https://github.com/jacobwagner"><img src="https://avatars.githubusercontent.com/u/2229998?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jacobwagner](https://github.com/jacobwagner)**
_Tuesday Aug 26, 2014 at 22:00 GMT_
_Originally opened as https://github.com/rcbops/ansible-lxc-rpc-orig/issues/477_

---

here is the only log i could find and it was on the page

```
Error Could not contact Elasticsearch at https://192.168.96.10:8443/elasticsearch/. Please ensure that Elasticsearch is reachable from your system
```

192.168.96.10 is the internal vip

**Comment by mancdaz** [comment]
<a href="https://github.com/d34dh0r53"><img src="https://avatars.githubusercontent.com/u/248299?v=2" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [d34dh0r53](https://github.com/d34dh0r53)**
_Tuesday Aug 26, 2014 at 22:19 GMT_

---

This actually looks correct in the play, can you show me your rpc_user_config.yml and any overrides you're using?  The variable external_vip_address needs to be defined.

**Comment by mancdaz** [comment]
<a href="https://github.com/andymcc"><img src="https://avatars.githubusercontent.com/u/1507326?v=2" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [andymcc](https://github.com/andymcc)**
_Wednesday Aug 27, 2014 at 08:13 GMT_

---

You need to set your external_lb value to the "external" IP then it should work. I had the same problem on mine.

**Comment by andymcc** [comment]
@jacobwagner any issues with the above?

**Comment by cloudnull** [comment]
marked invalid, reopen if needed.
