### ISSUE TITLE
Incorrect permissions on glance-api.log

### ISSUE THREAD

**Issue by ionosphere80** [rcbops/ansible-lxc-rpc#360]
On 10.0.0rc1, incorrect permissions on /var/log/glance/glance-api.log prevent the glance-api service from starting. Change permissions from root:root to glance:glance or run 'glance-manage db_sync' as the glance user.

**Comment by mattt416** [comment]
Closing this in favour of https://github.com/rcbops/ansible-lxc-rpc/issues/497.
