### ISSUE TITLE
Horizon problem creating lock file

### ISSUE THREAD

**Issue by ionosphere80** [rcbops/ansible-lxc-rpc#362]
On 10.0.0rc1, Apache returns a 500 error when attempting to access the dashboard. Upon further investigation, horizon fails to create a lock file... perhaps due to permissions issues.

From /var/log/horizon/horizon-error.log in the horizon container:

[Tue Oct 21 18:00:11.577765 2014] [:error] [pid 1029:tid 140005825554176] [client 10.1.11.11:59787] LockFailed: failed to create /usr/local/lib/python2.7/dist-packages/openstack_dashboard/local/infra1_horizon_container-402e95f5-a57fa700.1029-1456264493302339885

**Comment by mattt416** [comment]
Hi @ionosphere80, it looks like I created this issue when working on https://github.com/rcbops/ansible-lxc-rpc/pull/271.  I did find another odd issue in that the container_common role does a recursive chown on /usr/local/lib/python2.7/dist-packages/ to {{ system_user }}:{{ system_group }}, which in horizon's case is www-data:www-data.  So, if you run openstack-setup.yml twice you will end up with everything in /usr/local/lib/python2.7/dist-packages/ being owned by www-data:www-data (which is perhaps how I didn't catch this issue).  I'll create a separate issue for that.

**Comment by mattt416** [comment]
This will need to get backported to proposed/juno.

**Comment by sigmavirus24** [comment]
Alternatively, this could be fixed by not using `LOCAL_PATH` in `SECRET_KEY = secret_key.generate_or_read_from_file(os.path.join(LOCAL_PATH, '.secret_key_store'))`. Distribution packages like Ubuntu's use `/var/lib/openstack-dashboard/secret_key` (hat-tip to @ionosphere80)

**Comment by mattt416** [comment]
PR #366 has been updated.

**Comment by ionosphere80** [comment]
Backport to proposed/juno.
