### ISSUE TITLE
Incorrect permissions on /var/lib/glance/images

### ISSUE THREAD

**Issue by ionosphere80** [rcbops/ansible-lxc-rpc#364]
On 10.0.0rc1 using the 'file' store, incorrect permissions on /var/lib/glance/images causes strange errors. Change permissions from root:root to glance:glance.

**Comment by mattt416** [comment]
Hi @ionosphere80 ,

We don't explicitly create /var/lib/glance/images via ansible.  It looks like this creation happens in https://github.com/openstack/glance_store/blob/master/glance_store/_drivers/filesystem.py#L186.  On my cluster, I see:

```
glance-api.log:2014-11-11 21:36:35.636 1017 INFO glance_store._drivers.filesystem [-] Directory to write image files does not exist (/var/lib/glance/images/). Creating.
```

Assuming glance-api is started with a non-root user, this _should not_ be an issue.

We could explicitly create /var/lib/glance/images, but I'm not sure what negative implications this would have?
