### ISSUE TITLE
Python clients not installed from source

### ISSUE THREAD

**Issue by andymcc** [rcbops/ansible-lxc-rpc#365]
https://github.com/rcbops/ansible-lxc-rpc/commit/ca2173ecf49b93dbb8ef2af8512579cc3f2e0f1f was added to adjust the SHA for python-neutronclient, but python-neutronclient is still installed by pip.

For the utility servers we'd have to run the openstack-common play against the vars files for each individual client to do the source builds and remove the clients from the pip installs - and ensure these aren't being installed by pip elsewhere (for example neutron installs python-neutronclient so you would have inconsistent versions if they don't both do this from source).

We could probably tag the install_from_source task and then run supplying the appropriate vars (each client already has its own vars in vars/repo_packages)

**Comment by andymcc** [comment]
There probably needs to be a better way than running 1 task per client install.

**Comment by cloudnull** [comment]
@andymcc - In the playbooks pip is installing the clients from the "http://rpc-slushee.rackspace.com/python_packages/<RELEASE_BRANCH>" for it's source of packages. While all of the client listings in the repo_packages directory and could be used in playbooks most of them are exclusively used in the python wheel builder script found here: "https://github.com/rcbops/ansible-lxc-rpc/blob/master/scripts/rpc-wheel-builder.py". We did rebuilt all of the wheels from their respected branches when we released the "purposed/juno" and "9.0.1" tags but we are sadly in the limbo of waiting for cloudfiles to grace us with an updated index.  While waiting for the new blessed index you can override the repo url in the file `/etc/rpc_deploy/user_variables.yml` which has an instantly updating index. 

``` yaml
rpc_repo_url: http://rpc.cloudnull.io
```

**Comment by cloudnull** [comment]
Closing this issue as the client wheels are built from source and installed from the frozen repo.
