### ISSUE TITLE
{{ install_lib_dir }} owned by www-data:www-data on horizon containers

### ISSUE THREAD

**Issue by mattt416** [rcbops/ansible-lxc-rpc#367]
This is due to rpc_deployment/inventory/group_vars/horizon.yml having {{ install_lib_dir }} listed in container_directories.

**Comment by mattt416** [comment]
This should be backported to proposed/juno.

**Comment by ionosphere80** [comment]
Backport to proposed/juno.

**Comment by stevelle** [comment]
@mattt416 looks like this can be closed again as the patch is now in proposed/juno, but will let you confirm and push butan
