### ISSUE TITLE
Pip dependencies for MaaS error on install

### ISSUE THREAD

**Issue by andymcc** [rcbops/ansible-lxc-rpc#370]
MaaS requires lxml 3.3.5:

  Could not find a version that satisfies the requirement lxml==3.3.5 (from -r /usr/lib/rackspace-monitoring-agent/plugins/requirements.txt (line 3)) (from versions: 3.4.0)
Cleaning up...
No distributions matching the version for lxml==3.3.5 (from -r /usr/lib/rackspace-monitoring-agent/plugins/requirements.txt (line 3))
Storing debug log for failure in /root/.pip/pip.log

**Comment by andymcc** [comment]
This is related to the default maas_repo_version being "v9.0.0" instead of master in user_variables. So we should just change the default.

**Comment by mattt416** [comment]
@mancdaz do we point maas_repo_version in stable/icehouse and proposed/juno to their respective branches or to the 9.0.x and 10.0.x tags?

**Comment by cloudnull** [comment]
this is also related to Issue https://github.com/rcbops/ansible-lxc-rpc/issues/255.
