### ISSUE TITLE
haproxy play fails when no swift-proxy

### ISSUE THREAD

**Issue by andymcc** [rcbops/ansible-lxc-rpc#375]
hap_backend_alg': 'source', 'hap_service_name': 'kibana_ssl'}})
fatal: [node1] => One or more undefined variables: 'dict object' has no attribute 'swift_proxy'

FATAL: all hosts have already failed -- aborting

We need to default this to a string so the endpoint is created for haproxy even though it won't work.

**Comment by cloudnull** [comment]
I think "https://github.com/hughsaunders/ansible-lxc-rpc/commit/94896a850616fc7ac3559ecc2296bc25ebaed3f3" is a more suited solution to the problem however the HAproxy plays are not intended for production use so it doesn't really matter. Because the issue is fixed I'm closing it.
