### ISSUE TITLE
Neutron DHCP lease traffic being blocked at neutron_agents_container

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/ansible-lxc-rpc#383]
After an upgrade from 9.0.0 to 9.0.1, dhcp leases for vm networks stopped working.

I was able to fix the leasing via stopping and restarting both neutron agent containers, but I was not able to track down the root cause.

I am seeing multiple CRON jobs for the l3 and dhcp agent script. Not sure if this is the cause of the issue but I believe it is not.

I will continue to trobleshoot our broken labs to try to determine what in the upgrade caused this to happen.

Here is a gist of what was running post upgrade

https://gist.github.com/jacobwagner/54866c63687220ce80b6

**Comment by cloudnull** [comment]
@jacobwagner This should now be resolved in master, Juno, and Icehouse. That said to test the changes in 9.0.1 you will need to pull from the **stable/icehouse** branch.
