### ISSUE TITLE
9.0.0 galera_check has no alarms

### ISSUE THREAD

**Issue by bjoernt** [rcbops/ansible-lxc-rpc#403]
The maas galera_check did not get installed with an alarm in 9.0.0

**Comment by cloudnull** [comment]
Resolved with PR https://github.com/rcbops/ansible-lxc-rpc/pull/406, https://github.com/rcbops/ansible-lxc-rpc/pull/418, and https://github.com/rcbops/ansible-lxc-rpc/pull/419.
