### ISSUE TITLE
Spice endpoint should be configurable

### ISSUE THREAD

**Issue by bjoernt** [rcbops/ansible-lxc-rpc#409]
For security reasons we might want to run the spice proxy only internally. But currently the playbooks hard-code nova_html5proxy_base_url: "http://{{ external_vip_address }}:6082/spice_auto.html" to the external VIP. That should be configurable and only use external_vip as fallback.

**Comment by claco** [comment]
@BjoernT @cloudnull So, by default, the "external_vip_address" is the F5 VIP, which still requires people to VPN into their network first, before it's available.  What would we use if it wasn't the VIP?

**Comment by bjoernt** [comment]
In our case it was the external VIP

**Comment by cloudnull** [comment]
what @claco said is true. The "external_vip_address" should be the floating vip address of the load balancer. If the external_vip_address was set to the public ip, it was set incorrectly.

**Comment by bjoernt** [comment]
The external IP is going to a VIP so we would have internal_lb_vip_address and external_vip_address configured the same? I our case this would be the 172.29 address

**Comment by claco** [comment]
I summon @busterswt

**Comment by claco** [comment]
@cloudnull That's not how this works. :-P

**Comment by busterswt** [comment]
The external VIP will be whatever IP the client is expected to hit as a result of the publicurl returned by keystone. If all clients are coming from the Internet, the VIP address would need to be the public IP. If all clients come over VPN, it can usually be an private RFC1918 addr. This really depends on who the client is expected to be. We can't provide a private addr as the external VIP and expect it to work for outside clients - the addr isn't routeable.

In most cases we are configuring 172.29.236.9 for the 'external' VIP on the F5, and this could NAT to a public IP on the ASA. That public IP would need to be the IP used as the external_vip_address.
