### ISSUE TITLE
Cinder service created when there are no storage_hosts

### ISSUE THREAD

**Issue by evanstoner** [rcbops/ansible-lxc-rpc#416]
Cinder is [referred](http://docs.rackspace.com/rpc/api/v9/bk-rpc-installation/content/sec_overview_host-layout.html) [to](http://docs.rackspace.com/rpc/api/v9/bk-rpc-installation/content/sec_overview_requirements.html) [as](http://docs.rackspace.com/rpc/api/v9/bk-rpc-installation/content/sec-config-lvm.html) [optional](http://docs.rackspace.com/rpc/api/v9/bk-rpc-installation/content/sec-playbooks-openstack-run.html) throughout the RPC install guide. My team installed RPC with the storage_hosts section and storage network commented out in rpc_user_config.yml but cinder was still partially configured:
- infra1_cinder_api_container exists
- cinder and cinderv2 are show as enabled in horizon "System Info" (similar results from `keystone service-list`)
- horizon displays errors such as "unable to retrieve volume list" and, most importantly, fails when submitting the "Launch Instance" form

This is easily fixed by executing `keystone service-delete cinder` and `keystone service-delete cinderv2`. However, it seems that without any storage_hosts, cinder should not be configured at all.

**Comment by cloudnull** [comment]
Hi @evanstoner, presently the Openstack apis are all wrapped up in the one infrastructure group which is determined by the `rpc_environment.yml` file. If you are looking for a way to instruct ansible to never build the cinder containers on your infrastructure nodes and to not install the cinder-api and the cinder-scheduler services you can remove the the cinder container groups from the **container_skel** on the following lines, "https://github.com/rcbops/ansible-lxc-rpc/blob/master/etc/rpc_deploy/rpc_environment.yml#L132-L142". Alternatively you can create a new group that could be used in the future to further break the environment out. Being that this file lives outside of ansible's play-books it was created with configuration changes in mind. However any changes made to environment file will require you to update the `rpc_user_config.yml` with the new MD5 sum of the changed environment file.

We are looking into how we could could better break out the service groups and common infrastructure groups which will involve changes in the `rpc_environment.yml` but we've not created code that will do that just yet.
