### ISSUE TITLE
max_connections too low on mariadb instances ?

### ISSUE THREAD

**Issue by bjoernt** [rcbops/ansible-lxc-rpc#429]
Max_connections seems small, on a normal RPC customer deployments. We count already 340 sleeping mysql connections and from time to time I see max connection errors in various logs, especially nova related services seem to consume more resources. Maybe the max_connection should be dynamic based on the number of compute node we add. Memory is certainly enough for supporting bigger workloads

**Comment by cloudnull** [comment]
This is being resolved with PR https://github.com/rcbops/ansible-lxc-rpc/pull/444

**Comment by cloudnull** [comment]
This has been resolved. While I'm closing the issue please feel free to reopen it if needed.
