### ISSUE TITLE
[Support] - Managing LXC hosts

### ISSUE THREAD

**Issue by cloudnull** [rcbops/ansible-lxc-rpc#434]
Managing hosts with LXC can be difficult when there are potential issues with iptables, bridges, veths, dnsmasq and bulk container starts/stops. Support has asked for a tool that could be installed on all hosts that would allow for common operational tasks to be automated with simple bash commands.  Presently the lxc init scripts will only recreate LXC networks, start dnsmasq, and build the lxc bridge on host power on and off however support would like to have some tooling to easily perform most of these tasks without having to delve too deeply into the internal works of LXC.

**Comment by sigmavirus24** [comment]
Fixed in #435, backported in #440 and #441
