### ISSUE TITLE
Galera holland backup cronjob is not working

### ISSUE THREAD

**Issue by bjoernt** [rcbops/ansible-lxc-rpc#456]
Change holland_backups cron job from
# Ansible: holland-backup

2 \* \* \* 5 root holland bk

to
# Ansible: holland-backup

2 */2 \* \* \* root /usr/local/bin/holland bk

The /usr/local/bin path is not in the system PATH so holland needs to be called fully qualified.
Additionally we should to a backup every 2 hours or maybe every 4 housrs, once a week is way to unsafe

**Comment by claco** [comment]
This is fixed in 9.0.1 https://github.com/rcbops/ansible-lxc-rpc/pull/323

**Comment by claco** [comment]
Closing for now. Please re open if you find the new cron is not working or not applied after upgrading to 9.0.1
