### ISSUE TITLE
Create a variable for storage_availability_zone 

### ISSUE THREAD

**Issue by ihavegerms** [rcbops/ansible-lxc-rpc#458]
X will be doing most of their work from the dashboard and want to be able to specify which of their Cinder nodes they'll be creating block devices on. With how things are currently configured, all cinder nodes are part of the default "Nova" availability zone. The variable could/would be able to hold a few values to define different availability zones.

At this point, I've manually modified /etc/cinder/cinder.conf on each (2) of the cinder nodes to the first part of the hostname (prior to the underscore) as seen below (the change does require the cinder-volume containers to be restarted);

| cinder-scheduler |   604001-cinder1_cinder_volumes_container-bd45f3e0   | 604001-cinder1 | enabled |   up  | 2014-11-01T02:35:18.000000 |       None      |
| cinder-scheduler |   604009-cinder2_cinder_volumes_container-4bb88f1e   | 604009-cinder2 | enabled |   up  | 2014-11-01T02:35:02.000000 |       None      |
|  cinder-volume   | 604001-cinder1_cinder_volumes_container-bd45f3e0@lvm | 604001-cinder1 | enabled |   up  | 2014-11-01T02:35:10.000000 |       None      |
|  cinder-volume   | 604009-cinder2_cinder_volumes_container-4bb88f1e@lvm | 604009-cinder2 | enabled |   up  | 2014-11-01T02:35:04.000000 |       None      |

With an obvious pitfall... if the containers were for whatever reason destroyed, re-creation would erase anything statically defined.

**Comment by JCallicoat** [comment]
We can do this with cinder multi-backends, which are already supported by the playbooks[1], though I have no idea if/how well it works with Horizon.

I seem to recall @cloudnull telling me how to stick arbitrary variables in configs, but I don't remember the details. I'm helpful.

[1] https://github.com/rcbops/ansible-lxc-rpc/blob/master/etc/README.rst#adding-options-to-containers-within-targeted-hosts
https://wiki.openstack.org/wiki/Cinder-multi-backend
http://docs.openstack.org/admin-guide-cloud/content/multi_backend.html

**Comment by cloudnull** [comment]
@ihavegerms @JCallicoat Please review https://github.com/rcbops/ansible-lxc-rpc/pull/459 to make sure it fits the use case for the customer. If all is well then we may need to think about backporting to 9.0.x

**Comment by cfarquhar** [comment]
@cloudnull #459 fits the use case for this customer.  Please backport to 9.0.x.

**Comment by sigmavirus24** [comment]
Fixed in #459, backported in #467 and #466

**Comment by cloudnull** [comment]
This issue is remaining open as there is a doc impact per issue: https://github.com/rcbops/privatecloud-docs/issues/721
