### ISSUE TITLE
Lower overcommit ratios

### ISSUE THREAD

**Issue by bjoernt** [rcbops/ansible-lxc-rpc#470]
See nova_cpu_allocation_ratio at inventory/group_vars/nova_all.yml and lower that from 10.0 to 2.0
2.0 seems to be the most requested ratio.

**Comment by bjoernt** [comment]
Additionally set RAM overcommit ratio to 1.0

**Comment by claco** [comment]
Sounds like these types of settings should be templated, so we can tweak them per compute/customer/installation.

**Comment by bjoernt** [comment]
Yes templeting is ok, as long as we don't use such high default values

**Comment by mattt416** [comment]
Would it be prudent to get someone else in support to :+1: this request?

**Comment by mancdaz** [comment]
@BjoernT @mattt416 @claco These are [already templated](https://github.com/rcbops/ansible-lxc-rpc/blob/master/rpc_deployment/inventory/group_vars/nova_all.yml#L71-L75), and the default cpu_allocation_ratio was already dropped to 5.0 in master [here](https://github.com/rcbops/ansible-lxc-rpc/commit/f2e5946e2acc42acc0ecb42604a2b0be8f468ec0)

We can either cherry pick that commit into the 9.x series and include in the next tag release, or change the default to something else in both current master and 9.x series. As @mattt416 says though, perhaps a support consensus is required before we change those defaults.

**Comment by bjoernt** [comment]
Added @cfarquhar if he shares the same opinion as me

**Comment by b3rn4rd0s** [comment]
@klevenstein Has doc impact.

**Comment by cfarquhar** [comment]
Per discussion, this is templated in 9.0.1.  We should use 2:1 for default CPU overcommit and make sure the proper way to override is documented.

**Comment by mancdaz** [comment]
@cfarquhar actually whilst this is a group var that is changeable, it needs to be moved into the user_variables file so that updates don't clobber the manual change to the group_var (ie I was somewhat mistaken above)

I'll get the default cpu overcommit changed to 2:1 if that is the consensus, and the memory overcommit default set to 1:1, and move both of those into the user_variables file for easy overriding.

**Comment by klevenstein** [comment]
We don't currently have overcommit ratios documented, but can add. At what stage of the process (foundation, infra, or OpenStack playbooks) does this need to be specified?

**Comment by bjoernt** [comment]
Overcommit ratios can be configured along rpc_user_config configuration since it's primarily a first time configuration. Technically it belongs to the openstack. I can't think of having seen a openstack specific configuration, so we either append it after the rpc_user_config or open a new paragraph for this, just openstack related configuration. I can imagine that wouldn't be the only parameters we have to change openstack related
