### ISSUE TITLE
Compute nodes fail to build `authorized_keys` file

### ISSUE THREAD

**Issue by jpmontez** [rcbops/ansible-lxc-rpc#478]
The `nova_compute_sshkey_create` role fails at its last step: building the `authorized_keys` file. This is due to an intentional limitation.

Ansible prevents itself from creating files that don't exist beforehand; therefore, while that last step is correct in its implementation, a file has to be `touch`-ed beforehand in order for the redirection to work.

**Comment by claco** [comment]
Can you confirm the installed ansible version?

**Comment by jpmontez** [comment]
```
root@569037-infra01:~/ansible-lxc-rpc/rpc_deployment# ansible --version
ansible 1.6.10
```

Is this the correct version?

**Comment by jpmontez** [comment]
The relevant playbook where this occurs: https://github.com/rcbops/ansible-lxc-rpc/blob/10.0.0rc2/rpc_deployment/roles/nova_compute_sshkey_create/tasks/main.yml

The specific step is: "Build authorized keys"

**Comment by claco** [comment]
All merged and backported. Waiting on qe verificaiton.

**Comment by jpmontez** [comment]
This has been verified as working by QE.
