### ISSUE TITLE
Address addition of new user_variables

### ISSUE THREAD

**Issue by andymcc** [rcbops/ansible-lxc-rpc#49]
If we add new user_variables we need a sensible way of notifying the end-user as these won't be in the "/etc/rpc_deploy/user_variables.yml" file and will cause runs to fail.

We currently do a version check on the inventory vs environment vs rpc_user_config files, we should probably consider doing this with the user_variables also.

**Comment by cloudnull** [comment]
I think that it may be time revisit the `user_variables.yml` file and move all config options into global overrides in the `rpc_user_config.yml` file and leave only passwords, tokens, keys, ect... This way we could simply have one config file and one key file. thoughts?

**Comment by claco** [comment]
Only speaking for myself, at first pass, we point people to user_config first. I expect global overrides in user_config to actually globally override things in user_variables, which it doesn't if it exists in both places?.

I guess the separation of the two should also be re evaluated against past requirement that we might be auto generating one, or both of those files from CORE and other sources of pre configuration information.
