### ISSUE TITLE
rpc-wheel-builder.sh not executable by default

### ISSUE THREAD

**Issue by claco** [rcbops/ansible-lxc-rpc#490]
Seems like all of the .sh files in ./scripts are executable after clone, except for `rpc-wheel-builder.sh`

Also, seems that it's hardcoded to look for `/opt/rpc-wheel-builder.py`, and should likely be `./scripts/rpc-wheel-builder.py` or some variant instead.

**Comment by d34dh0r53** [comment]
What about an RPC_PATH environment variable that is set at the beginning of the file that is referenced in the execute string?

**Comment by d34dh0r53** [comment]
Actually looking at it, the WORK_DIR is where the repo is cloned so the wheel builder scripts are located there, submitting a patch that changes the hardcoding to use that.

**Comment by cloudnull** [comment]
I am closing this issue because this script as well as its accompanying python script has been moved into the files directory of the **pkg_repo_sync_master** role. In PR: https://github.com/rcbops/ansible-lxc-rpc/pull/543 which automates the setup and use of the wheel builder applications.
