### ISSUE TITLE
stable/icehouse version of cloudserver-aio.sh pulls master branch by default

### ISSUE THREAD

**Issue by nrb** [rcbops/ansible-lxc-rpc#493]
This behavior likely does not affect customers, but can affect those of us who try to build AIOs based on different versions.

Since the names and layouts of playbooks differ between `master` and `stable/icehouse`, I think the `cloudserver-aio.sh` script should default to `stable/icehouse` on that branch, rather than master.

**Comment by sigmavirus24** [comment]
Should probably port this to `proposed/juno` too

**Comment by nrb** [comment]
Good point; IMO, the `cloudserver-aio.sh` script in each branch should point to that branch.

**Comment by sigmavirus24** [comment]
I bet we could write something to parse the branch from the git information

**Comment by nrb** [comment]
Well, the issue's not solely the branch name. The names of the other files, especially playbooks, will also have to be valid for that branch.

**Comment by nrb** [comment]
Also, if you run this via the heat template, the script is downloaded separately from the repo, as seen here: https://github.com/rcbops/ansible-lxc-rpc/blob/stable/icehouse/scripts/rpc9.0.0-aio-rax-heat-template.yml#L77

**Comment by nrb** [comment]
One thought would be to edit the heat template to use the `repo_branch` string when building the `install_script_url` variable.

**Comment by sigmavirus24** [comment]
True, we also need to make sure `rpc_user_config.yml` is correct for each.

**Comment by cloudnull** [comment]
Presently this issue has been resolved as the branch bits have been corrected in master. @sigmavirus24  @nrb we may want to review how the `rpc_user_config.yml` is being built in our various releases and if it needs updating we should open another issue.
