### ISSUE TITLE
Only one horzion container working out of 3

### ISSUE THREAD

**Issue by bjoernt** [rcbops/ansible-lxc-rpc#495]
Just did a clean 9.0.1 build and noticed that not all horizon container have horizon running. When I ran horizon-all on the 2nd container it stops with:

PLAY [horizon_all:!horizon_all[0]] *******************************************\* 

TASK: [Retrieve apache keys] *************************************************\* 
failed: [626973-Infra02_horizon_container-6eb4a82e] => (item={'src': '/etc/ssl/private/apache.key', 'name': 'apache_key', 'file_mode': '0640', 'dir_mode': '0750'}) => {"err": "Memcache key not found", "failed": true, "item": {"dir_mode": "0750", "file_mode": "0640", "name": "apache_key", "src": "/etc/ssl/private/apache.key"}, "rc": 1}
msg: The key you specified was not found within memcached. If you are load balancing memcahced, attempt to connect to a single node.
failed: [626973-Infra02_horizon_container-6eb4a82e] => (item={'src': '/etc/ssl/certs/apache.cert', 'name': 'apache_cert', 'file_mode': '0644', 'dir_mode': '0755'}) => {"err": "Memcache key not found", "failed": true, "item": {"dir_mode": "0755", "file_mode": "0644", "name": "apache_cert", "src": "/etc/ssl/certs/apache.cert"}, "rc": 1}
msg: The key you specified was not found within memcached. If you are load balancing memcahced, attempt to connect to a single node.

**Comment by bjoernt** [comment]
I saw the apache is running on all containers now, that might be enough for now.
The horizon-all still should finish tough

**Comment by mancdaz** [comment]
Hi @BjoernT can you confirm if this is still a repeatable issue?

**Comment by mattt416** [comment]
Hi @BjoernT,

I just deployed 9.0.3 and 10.0.0rc4 and did not see this behaviour on either installation.  I'm going to go ahead and close this issue but please feel free to grab me should you feel this is still an issue.  I'll gladly re-open the bug report then.

Thanks!

--Matt
