### ISSUE TITLE
Ownership of glance-api.log by root prevents service from starting up

### ISSUE THREAD

**Issue by ionosphere80** [rcbops/ansible-lxc-rpc#497]
The 'glance-manage db_sync' command writes output to the /var/log/glance-api.log file. Since the file doesn't exist and the command runs as root, the file gets created with root ownership. However, the glance-api service runs as the glance user and ownership of the log file by root prevents it from starting up. Issue valid on 10.0.0rc3.

**Comment by claco** [comment]
Was this an issue in 9.x, or something that just started in Juno, or with some setup we're doing different in 10.x?

**Comment by ionosphere80** [comment]
I don't see the issue in 9.0.2 or 10.0.0rc1.

**Comment by ionosphere80** [comment]
We should probably run the database sync commands for all services as the service user.

**Comment by sigmavirus24** [comment]
> We should probably run the database sync commands for all services as the service user.

Are we not?

**Comment by ionosphere80** [comment]
After a quick look, no... except for maybe keystone. The database sync command for most services creates a separate *-manage.log file (or log nothing at all) that the services themselves don't use and therefore successfully start up regardless of ownership.

**Comment by ionosphere80** [comment]
Opened upstream bug: https://bugs.launchpad.net/glance/+bug/1391211

**Comment by mattt416** [comment]
This is not causing any breaking issues on stable/icehouse from what I can tell, so treating this more as an enhancement and not backporting to stable/icehouse.
