### ISSUE TITLE
server resizing does not work

### ISSUE THREAD

**Issue by jcannava** [rcbops/ansible-lxc-rpc#5]
On the IAD labs, when resizing a running instance, the resize target enters an error state

Excerpt from nova-compute.log on the compute host (including stacktrace):
https://gist.github.com/jcourtois/b68175881fa6fceb2fdf

I think this is the necessary fix:
https://bugzilla.redhat.com/show_bug.cgi?id=975014

**Comment by jacobwagner** [comment]
reopen, see issue #6

**Comment by jcourtois** [comment]
This works on Kevin's fix; we can close when that PR is accepted.

**Comment by jacobwagner** [comment]
fixed in PR #72, closing
