### ISSUE TITLE
Fully automate cinder netapp provisioning

### ISSUE THREAD

**Issue by bjoernt** [rcbops/ansible-lxc-rpc#506]
Please populate /etc/nfs/nfs_shares in the cinder-volumes container if the cinder_backed is netapp according this scheme  netapp_server_hostname:<netapp_server_volume>
A valid path can look like : 172.16.0.10:/vol/cinder
The netapp_server_volume token is currently not existing and need to be added, name can be altered, it's just an example.
Additionally the package nfs-common need to be installed in the cinder-volumes container and all hosts
This needs to be back ported to icehouse

**Comment by b3rn4rd0s** [comment]
@klevenstein Has doc impact.

**Comment by miguelgrinberg** [comment]
@BjoernT: I need some clarifications if you don't mind. These are the action items I extracted from your comment:
1. Create nfs_shares file in the cinder hosts if NFS is the selected protocol. 
   - Question: I guess we need new items in the configuration for the IP address and share?
2. Install nfs-common in the cinder hosts if NFS is the selected protocol.
3. `netapp_server_volume` needs to be added to the configuration.
   - Can you explain what is this for? Or if this is documented somewhere please let me know where.

**Comment by bjoernt** [comment]
@miguelgrinberg I think we can reuse netapp_server_hostname for he IP but we would need a new token for the volume path, in this case I made the example netapp_server_volume. Cinder uses the nfsshares file to mount the filer under /var/lib/cinder/mnt so it can create the disk files or get the statistics about this volume like space utilization. Also I had some documentation in the RPC wiki under 9.0 tips/tricks

**Comment by miguelgrinberg** [comment]
Ah, I see. You mention the word "token" and I assumed you were now talking about a different thing, sorry.

Do you know if it is valid to write a hostname instead of an IP address in the nfs_shares.txt file? Our `netapp_server_hostname` can be given as IP or hostname, if only IPs are allowed I'll have to resolve the name.

Also, I will not be able to test this other than by looking at the config files produced, as I don't have access to a  netapp appliance. Can I send you a patch when I have it so that you can verify?

**Comment by bjoernt** [comment]
I referred to it as token since it'll be used in the template as as token to replace it the content if this variable. Sorry about that. IP or DNS, either way works. There is no requirement to use only IPs but we probably to it here since we mostly don't have one. I can verify just from the produced files, since we only have a netapp in prod I can't apply that in prod yet. But feel free to commit this issue and I pull the patch myself to test

**Comment by klevenstein** [comment]
We've made some updates to the NetApp doc that can be reviewed here:
http://docs-internal-staging.rackspace.com/rpc/api/v9/bk-rpc-installation/content/sec_configure-cinder.html
please review and let us know if there's anything we missed.

**Comment by miguelgrinberg** [comment]
Karin, I think there's going to be some changes needed. We are going to write the NFS configuration separately from the netapp configuration, so at least one item you have there, the `nfs_shares_config` will go in a different location, and there's going to be a new cinder sub-section with this and other items specific to NFS.

But before you make any changes let me finish what I'm doing (likely today) and have a PR out that others can review.

**Comment by klevenstein** [comment]
Miguel: thanks! We're currently tracking netapp docs things here: https://github.com/rcbops/privatecloud-docs/issues/715
Feel free to add to that issue as things progress.

**Comment by cloudnull** [comment]
@miguelgrinberg  has done a lot of the work to automated NFS + Cinder which is directly related to using Netapp + NFS + Cinder. Just to add to the conversation here is the current PR into master https://github.com/rcbops/ansible-lxc-rpc/pull/563

**Comment by miguelgrinberg** [comment]
And I posted a summary of the documentation changes required to match these changes in a comment for rcbops/privatecloud-docs#715.
