### ISSUE TITLE
nova-consoleauth needs to use memcached

### ISSUE THREAD

**Issue by mattt416** [rcbops/ansible-lxc-rpc#52]
This is required since we run multiple memcached servers.  Whilst we specify memcached_servers in nova.conf, this is under the `keystone_authtoken` and is not found by nova-consoleauth.

On a side note, should we specify memcached_servers to point to the memcached VIP, or to each individual memcached server?

**Comment by mattt416** [comment]
There was some discussion about enumerating memcached servers in memcached_servers rather than listing a single VIP -- further testing will need to be done here before that can be done.

**Comment by cloudnull** [comment]
The fix has been merged for this. We should open a new issue for refactoring the memcached servers variable if we think it's needed.
