### ISSUE TITLE
Point frozen repos to Rackspace mirrors

### ISSUE THREAD

**Issue by d34dh0r53** [rcbops/ansible-lxc-rpc#527]
We need to move the frozen repos to point to mirror.rackspace.com/rackspaceprivatecloud instead of rpc-slushee.rackspace.com.

**Comment by stevelle** [comment]
Backports are ready, the PRs are just waiting for acceptance of #528

**Comment by stevelle** [comment]
reopening for stable/icehouse and proposed/juno backports
