### ISSUE TITLE
Issues with the Frozen Repo [Missing or Incorrect packages]

### ISSUE THREAD

**Issue by cloudnull** [rcbops/ansible-lxc-rpc#53]
All of the packages from the mariadb apt-repos are missing, specifically: "deb http://mirror.jmu.edu/pub/mariadb/repo/5.5/ubuntu trusty main"

This makes it impossible to install "mariadb-galera-server-5.5" and it's supporting services.

**Comment by cloudnull** [comment]
Relates to PR: https://github.com/rcbops/ansible-lxc-rpc/pull/51

**Comment by aedan** [comment]
I am correcting the issue now.

**Comment by aedan** [comment]
This issue should now we fixed.

libmariadbclient-dev_5.5.38+maria-1~trusty_amd64.deb    1Mi     2014-08-13 15:29:32
libmariadbclient18_5.5.38+maria-1~trusty_amd64.deb  506Ki   2014-08-13 15:29:32
libmariadbd-dev_5.5.39+maria-1~trusty_amd64.deb     3Ki     2014-09-02 16:06:16
libmysqlclient18_5.5.38+maria-1~trusty_amd64.deb    3Ki     2014-08-13 15:29:33
mariadb-client-5.5_5.5.38+maria-1~trusty_amd64.deb  932Ki   2014-08-13 15:29:33
mariadb-client-core-5.5_5.5.38+maria-1~trusty_amd64.deb     708Ki   2014-08-13 15:29:33
mariadb-client_5.5.38+maria-1~trusty_all.deb    3Ki     2014-08-13 15:29:32
mariadb-common_5.5.38+maria-1~trusty_all.deb    3Ki     2014-08-13 15:29:32
mariadb-galera-server-5.5_5.5.39+maria-1~trusty_amd64.deb   8Mi     2014-09-02 16:06:15
mariadb-galera-server_5.5.39+maria-1~trusty_all.deb     3Ki     2014-09-02 16:06:15
mariadb-galera-test-5.5_5.5.39+maria-1~trusty_amd64.deb     15Mi    2014-09-02 16:06:16
mariadb-galera-test_5.5.39+maria-1~trusty_all.deb   3Ki     2014-09-02 16:06:15
mariadb-server-5.5_5.5.39+maria-1~trusty_amd64.deb  4Mi     2014-09-02 16:06:15
mariadb-server-core-5.5_5.5.39+maria-1~trusty_amd64.deb     4Mi     2014-09-02 16:06:15
mariadb-server_5.5.39+maria-1~trusty_all.deb    3Ki     2014-09-02 16:06:15
mariadb-test-5.5_5.5.39+maria-1~trusty_amd64.deb    21Mi    2014-09-02 16:06:15
mariadb-test_5.5.39+maria-1~trusty_all.deb  3Ki     2014-09-02 16:06:15
mysql-common_5.5.38+maria-1~trusty_all.deb  8Ki     2014-08-13 15:29:32

**Comment by cloudnull** [comment]
While the missing mariaDB packages have been resolved we are now hitting another packaging issue. It seems that we have packages installed that are incompatible packages based on the distro release.

``` bash
failed: [infra1_elasticsearch_container-ed7c4ab6] => (item=elasticsearch,openjdk-7-jre) => {"attempts": 3, "failed": true, "item": "elasticsearch,openjdk-7-jre"}
stderr: E: Unable to correct problems, you have held broken packages.

stdout: Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 openjdk-7-jre : Depends: openjdk-7-jre-headless (= 7u51-2.4.6-1ubuntu4) but it is not going to be installed

msg: Task failed as maximum retries was encountered

FATAL: all hosts have already failed -- aborting
```

In this case I've traced this issue to the package `tzdata`. The installed version on Ubuntu 14.04.01 is `2014e-0ubuntu0.14.04` however the package `openjdk-7-jre` depends on `openjdk-7-jre-headless` which depends on `tzdata-java` which depends on `tzdata` version `2014b-1`

**Comment by mancdaz** [comment]
resolved
