### ISSUE TITLE
Spike: Research Logstash Filtering/CPU

### ISSUE THREAD

**Issue by d34dh0r53** [rcbops/ansible-lxc-rpc#530]
The current filtering configuration for Logstash is excessively CPU intensive and unstable.  Work needs to be done to find a rework of the filtering mechanisms or to bypass them all together.

**Comment by odyssey4me** [comment]
It appears that the default number of logstash workers is 1. Perhaps adding a worker per cpu is a better option to improve efficiency. Additional workers are added by changing the `LS_OPTS` option in `/etc/default/logstash` to include `-w 8` (for 8 workers). The CPU utilisation in my test lab is still high though, so while the above setting will probably increase efficiency it appears that the only way to really reduce CPU utilisation is to reduce the complexity of the filters.

**Comment by odyssey4me** [comment]
FYI - logstash-web appears to be the thing that's causing the high cpu consumption. Can we live without it? See the top 5 java processes for logstash with the following:

```
ps -eLo pid,nlwp,pcpu,args | grep "$(ps -ef | awk '/[l]ogstash.*java/ {print $2}' | xargs | sed 's/ /\\\|/g')" | grep -v grep | sort -k 3 -rn | head -n 5
```

Shutting down the `logstash-web` service immediately drops CPU utilisation and the container runs happily. The extra workers addition to the config also makes the log processing very efficient.
