### ISSUE TITLE
Pip will not install requirements via http 

### ISSUE THREAD

**Issue by stevelle** [rcbops/ansible-lxc-rpc#531]
Gate is reporting an issue with us moving the frozen repo to mirror.rackspace.

> 22:51:27 TASK: [common | Install PIP] *************************************************\* 
> [...]
> 22:51:46 stdout: Ignoring indexes: https://pypi.python.org/simple/
> 22:51:46 http://mirror.rackspace.com/rackspaceprivatecloud/python_packages/master/ uses an insecure transport scheme (http). Consider using https if mirror.rackspace.com has it available
> 22:51:46 Could not find any downloads that satisfy the requirement pip in /usr/local/lib/python2.7/dist-packages
> 22:51:46 Downloading/unpacking pip
> 22:51:46 Cleaning up...
> 22:51:46 No distributions at all found for pip in /usr/local/lib/python2.7/dist-packages
> 22:51:46 Storing debug log for failure in /root/.pip/pip.log
> 22:51:46 msg: Task failed as maximum retries was encountered

see also:
http://jenkins.propter.net/job/dev-sat6-gate/317/console

Blocks #527 and #499

Issue doesn't appear to actually be with a lack of https.  Checking mirror for the requirements shows some gaps in places, which could be the cause.
Ex.
- http://rpc-slushee.rackspace.com/python_packages/master/cloudlib-0.0.8-py2-none-any.whl
- http://rpc-slushee.rackspace.com/python_packages/master/requests-2.4.1-py2.py3-none-any.whl

more to be discovered

**Comment by cloudnull** [comment]
this issue is being caused by the branch release version for the repo_package file for ansible-lxc-rpc pointing at a sha instead of itself. 

`repo_packages/ansible_rpc_lxc.yml` from stable/icehouse file:
https://github.com/rcbops/ansible-lxc-rpc/blob/stable/icehouse/rpc_deployment/vars/repo_packages/ansible_rpc_lxc.yml#L20

This points to the sha "22dd0baba7b1e0f496794ee59c968738df1a257d" that lacks the dependencies required to perform a modern build.

**Comment by nrb** [comment]
Does this have to be pinned at a SHA, or would pointing to the current branch/tag help?

**Comment by cloudnull** [comment]
In all honesty, it could be pointed at a sha it just needs to be a more updated sha. For the branches, I'd recommend that it be pointed at the branch.

**Comment by cloudnull** [comment]
As of this morning issues #527 and #499 should no longer be blocked when using rpc.cloudnull.io or mirror.rackspace.com. sadly rpc-slushee is likely still in a bad state due the perpetual CDN problems.

**Comment by stevelle** [comment]
no longer occurs for master.  General process issue to be addressed separately.
