### ISSUE TITLE
9.0.3

### ISSUE THREAD

**Issue by b3rn4rd0s** [rcbops/ansible-lxc-rpc#541]
- [x] Fix tag version repo issues (related to 10.0.0 rc4)
- [ ] Help QE ( @jpmontez @jcourtois ) with setting up on a dev lab so they can do automated QE gating for 9.0.3

**Comment by mancdaz** [comment]
9.0.3 tagged, and all the things pointed to the right place

https://github.com/rcbops/ansible-lxc-rpc/pull/565

**Comment by mancdaz** [comment]
I believe the doc impact for the release itself has been adressed, but adding label and leaving open for confirmation

**Comment by b3rn4rd0s** [comment]
We need someone to help @jcourtois and @jpmontez setup on one of our dev labs.

From @kaushikb:

Bernardo,

Please could you get a dev paired with James/Julian so that they can get tests running against a 9.0.3 endpoint ?

**Comment by jpmontez** [comment]
Yeah, can someone send the deployment node info to our email addresses, please?

**Comment by jacobwagner** [comment]
I am currently building our IAD3 Lab02 on 9.0.3 right now. Not sure if we want to do some runs there. should be done shortly.

**Comment by klevenstein** [comment]
We added the updates from the change log to the release notes, and can publish them anytime.

The new bits are here:

http://docs-staging.rackspace.com/rpc/api/v9/bk-rpc-releasenotes/content/v902.html
http://docs-staging.rackspace.com/rpc/api/v9/bk-rpc-releasenotes/content/v903.html
