### ISSUE TITLE
RPC Nimbus installer installs the snmptd probe but the config doesn't enable hardware monitoring

### ISSUE THREAD

**Issue by valw** [rcbops/ansible-lxc-rpc#562]
RPC Nimbus installer installs the snmptd probe but the config which is put in place hadn't any actual hardware monitoring enabled so failed harddrives, PSU, CPU, RAM didn't create tickets and largely went unnoticed unless DCOPs saw the failure in a Raid walk.

<<[REDACTED]>>

The config file will need to be updated and then the updated config will need to be rolled out to RPC customers using openstack-probes.pl

**Comment by mancdaz** [comment]
migrated this issue here: https://github.com/rcbops/support-tools/issues/35
