### ISSUE TITLE
Cinder Backup

### ISSUE THREAD

**Issue by b3rn4rd0s** [rcbops/ansible-lxc-rpc#570]
From @ryanyard 

Customer is requesting cinder-backup be configured for their cloud, is that something we will support? If so, can you help me configure it? I have the cinder.conf directives, was wanting a recommendation on where to run, was thing inside the volume container, how do I create an upstart script for the service?

From @cloudnull :

@jcannava , @claco , is this something we want to prioritize for this sprint?

To add cinder backup to the playbooks we would need to create a role that would enable it, IE add config, start services

Config looks like it would need to be a generator that supports three possible cinder backup services. I would assume that we would only support Swift:

http://docs.openstack.org/juno/config-reference/content/swift-backup-driver.html changes would be made to the /etc/cinder/cinder.conf

Cinder backup is a service that can be started and stopped with our standard upstart script generator.

IMHO this would be an addon play that was only run if the user ran it manually as cinder-backup is still an optional service according to the upstream openstack docs.

**Comment by b3rn4rd0s** [comment]
From @claco :

Given our looming customer deadlines, and the need to solidify and stabilize what we currently have, I would much prefer that we do not go down this path at the moment. The sprint it set, and I would like to get us back into the habit of not just adding work to each sprint without it first getting reviewed and prioritized by the larger group.

I'm not apposed to adding this feature, but I am concerned that sometimes these tasks take a little more time than originally anticipated. I would like to keep us focused on getting things stable and helping QE/Support through any issues around the 10.1.0 release itself over the next few
weeks.

Having said that, please add this as a github issue. We have recently started reviewing and prioritizing open issues as a group, with both support and devs coming to agreement on what things are priority1, p2, and p3. We need to also include someone from the se group in those
meetings.

**Comment by b3rn4rd0s** [comment]
From @mancdaz :

I tend to agree.  We are already behind on finalizing the 10.0.0 release due to some late issues that QE are finding, which we will need to prioritize. We also have a number of outstanding P1 issues that we need to get to for 10.1.0, the testing for which falls behind each day that we are
delayed on 10.0.0.

**Comment by jcannava** [comment]
+1 this needs to be prioritized in a later sprint.
