### ISSUE TITLE
How to deal with EOL'd Kernel

### ISSUE THREAD

**Issue by b3rn4rd0s** [rcbops/ansible-lxc-rpc#575]
From @jcannava :

How to deal with EOL’d Kernel. @b3rnard0 we will also need a card for this in the next sprint (I will open an issue in github). This issue is directly related to 4.x series customers. Over the past six months or so we have been upgrading customers to a specific kernel and OVS version that we know to be stable. Sometime in September Ubuntu release a patch that now includes an MOTD notification indicating to the customer that the kernel they are using will be EOL’d. So support has asked us if we can find a new matching Kernel/OVS version that works so that we can get off of the EOL’d kernel. That said I think our course of action here is to stabilize on what public cloud is using which I believe is OVS 2.3 and it’s corresponding kernel.

**Comment by jcannava** [comment]
Issue information: https://github.com/rcbops/chef-cookbooks/issues/976

**Comment by mancdaz** [comment]
moving here:

https://github.com/rcbops/u-suk-dev/issues/59
