### ISSUE TITLE
Nova API header change?

### ISSUE THREAD

**Issue by jcourtois** [rcbops/ansible-lxc-rpc#576]
I was wondering if someone could explain to me whether the Nova v2 API was supposed to have changed recently. The header `'x-compute-request-id'` is no longer present in HTTP responses from Nova API and this is causing some tests to break.

Nova API HTTP response circa August 2014:

<pre>
------------
REQUEST SENT
------------
request method..: POST
request url.....: http://10.127.101.28:8774/v2/64cd2b7f21334639987826553eed2a4f/servers
request params..:
request headers.: {'Content-Length': '219', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'User-Agent': 'python-requests/2.3.0 CPython/2.7.5 Darwin/13.3.0', 'X-Auth-Token': u'9b6b4805ec1f4067a27248899c6afb52', 'Content-Type': 'application/json'}
request body....: {"server": {"flavorRef": "2", "imageRef": "7d229326-dedf-4d30-8e9a-4b551aa083ce", "networks": [{"uuid": "7b2c596b-183f-4b51-9316-ff3da2d9381f"}], "security_groups": [{"name": "qe_default"}], "name": "testserver954504"}}

2014-08-12 17:02:56,879: DEBUG: cafe.engine.http.client:
-----------------
RESPONSE RECEIVED
-----------------
response status..: <Response [202]>
response time....: 0.503565073013
response headers.: {'date': 'Tue, 12 Aug 2014 22:02:57 GMT', 'content-length': '445', 'content-type': 'application/json', 'location': 'http://10.127.101.28:8774/v2/64cd2b7f21334639987826553eed2a4f/servers/18ef3c7b-e440-4218-a1aa-8b764ffc287e', <b>'x-compute-request-id': 'req-b620ec89-dc16-4d64-9bf7-29f18dd97c33'</b>}
response body....: {"server": {"security_groups": [{"name": "qe_default"}], "OS-DCF:diskConfig": "MANUAL", "id": "18ef3c7b-e440-4218-a1aa-8b764ffc287e", "links": [{"href": "http://10.127.101.28:8774/v2/64cd2b7f21334639987826553eed2a4f/servers/18ef3c7b-e440-4218-a1aa-8b764ffc287e", "rel": "self"}, {"href": "http://10.127.101.28:8774/64cd2b7f21334639987826553eed2a4f/servers/18ef3c7b-e440-4218-a1aa-8b764ffc287e", "rel": "bookmark"}], "adminPass": "[redacted]"}}
-------------------------------------------------------------------------------
</pre>

Nova API HTTP response now:

```
------------
REQUEST SENT
------------
request method..: POST
request url.....: http://10.127.101.61:8774/v2/a8b1ff235827484b9a9390bf1f003e7a/servers
request params..:
request headers.: {'Content-Length': '997', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'User-Agent': 'python-requests/2.4.3 CPython/2.7.6 Linux/3.13.0-39-generic', 'Connection': 'keep-alive', 'X-Auth-Token': '[redacted]', 'Content-Type': 'application/json'}
request body....: {"server": {"name": "server254746", "imageRef": "c93c78a8-1b88-44ba-b94d-12421663258d", "key_name": "key891325", "flavorRef": "2", "personality": [{"path": "'/'/test.txt", "contents": "VGhpcyBpcyBhIHRlc3QgZmlsZS4="}, {"path": "~/.ssh/authorized_keys", "contents": "[redacted]"}], "networks": [{"uuid": "2f3ad760-ac85-48ca-8686-d9174ab05f48"}], "security_groups": [{"name": "qe_default"}], "metadata": {"meta_key_1": "meta_value_1", "meta_key_2": "meta_value_2"}}}

2014-11-18 21:41:44,692: DEBUG: cafe.engine.http.client:
-----------------
RESPONSE RECEIVED
-----------------
response status..: <Response [202]>
response time....: 0.392634153366
response headers.: {'date': 'Tue, 18 Nov 2014 21:41:44 GMT', 'connection': 'keep-alive', 'content-type': 'application/json', 'content-length': '445', 'location': 'http://10.127.101.61:8774/v2/a8b1ff235827484b9a9390bf1f003e7a/servers/9314d685-39e4-40e1-b140-45f996d37e62'}
response body....: {"server": {"security_groups": [{"name": "qe_default"}], "OS-DCF:diskConfig": "MANUAL", "id": "9314d685-39e4-40e1-b140-45f996d37e62", "links": [{"href": "http://10.127.101.61:8774/v2/a8b1ff235827484b9a9390bf1f003e7a/servers/9314d685-39e4-40e1-b140-45f996d37e62", "rel": "self"}, {"href": "http://10.127.101.61:8774/a8b1ff235827484b9a9390bf1f003e7a/servers/9314d685-39e4-40e1-b140-45f996d37e62", "rel": "bookmark"}], "adminPass": "[redacted]"}}
-------------------------------------------------------------------------------
```

**Comment by mancdaz** [comment]
@jcourtois what release of openstack are you testing, and were you testing in August? I realise the API should not change between releases, but...some changes were made to support v3 api.  This commit may be related:

https://github.com/openstack/nova/commit/49d83e356afd6197fc95277f0d18723bdfa11652

**Comment by mancdaz** [comment]
Confirmed.  Will file a fix shortly

**Comment by mancdaz** [comment]
@jcourtois fix has been proposed to master. Is this blocking testing of 10.0.0rc4? If so, we can pull it into the juno branch and cut an rc5 for you

**Comment by jcourtois** [comment]
Thanks! The issue is blocking about 6 nova functional and nova-cinder integration tests. If it's not too much trouble, a 10.0.0rc5 would be great.

**Comment by mancdaz** [comment]
@jcourtois I believe this patch has been hand merged into the current rc4 deployment.  If rc4 passes, I can roll it into the 10.0.0 release tag.

**Comment by cloudnull** [comment]
This issue is resolved with the commits in master and proposed/juno as such I am closing this issue.
