### ISSUE TITLE
Nova user not setup correctly

### ISSUE THREAD

**Issue by ihavegerms** [rcbops/ansible-lxc-rpc#587]
While attempting to migrate a VM from one compute to another I ran in to the following error;

fault                                | {"message": "Unexpected error while running command.                                                                                             |
|                                      | Command: ssh 10.16.28.13 mkdir -p /var/lib/nova/instances/e24af2e7-2ab3-4036-ac74-66c39ae23d0f                                                   |
|                                      | Exit code: 1                                                                                                                                     |
|                                      | Stdout: ''                                                                                                                                       |
|                                      | Stderr: ''", "code": 500, "details": "  File \"/usr/local/lib/python2.7/dist-packages/nova/compute/manager.py\", line 290, in decorated_function |
|                                      |     return function(self, context, _args, *_kwargs)                                                                                              |
|                                      |   File \"/usr/local/lib/python2.7/dist-packages/nova/compute/manager.py\", line 3459, in resize_instance                                         |
|                                      |     block_device_info)                                                                                                                           |
|                                      |   File \"/usr/local/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py\", line 4939, in migrate_disk_and_power_off                          |
|                                      |     utils.execute('ssh', dest, 'mkdir', '-p', inst_base)                                                                                         |
|                                      |   File \"/usr/local/lib/python2.7/dist-packages/nova/utils.py\", line 165, in execute                                                            |
|                                      |     return processutils.execute(_cmd, *_kwargs)                                                                                                  |
|                                      |   File \"/usr/local/lib/python2.7/dist-packages/nova/openstack/common/processutils.py\", line 193, in execute                                    |
|                                      |     cmd=' '.join(cmd))                                                                                                                           |
|                                      | ", "created": "2014-11-20T00:14:51Z"}

as a result of running;

nova migrate <vm uuid>

To fix the issue, we had to change /bin/false for the nova user to /bin/bash. Once the change was complete, the migration started without issue.

**Comment by mattt416** [comment]
Hi @ihavegerms,

I just deployed 9.0.3 and 10.0.0rc4 and could not replicate this issue on either.  The nova user was created correctly on the compute nodes and I was able to migrate between nodes without issue.

Can you please confirm what version this installation is using?  It's likely that the environment was deployed prior to a fix going through for this.  If you can provide further details I'll double-check so we can be sure.

Thanks!

--Matt

**Comment by cloudnull** [comment]
At this time we can not reproduce the issue. We are closing this bug report for now but if the issues comes back please feel free to reopen it.
