### ISSUE TITLE
Should swift use rsync?

### ISSUE THREAD

**Issue by ionosphere80** [rcbops/ansible-lxc-rpc#589]
Swift typically uses rsync on the storage nodes. I see rsync installed, but it isn't configured or operational.

**Comment by andymcc** [comment]
I have a patch to implement the swift-docs version of rsync conf/setup. Before that happens though I'd like to find out what benefit this provides.. The replication is happening fine (you can see this by uploading an object and watching it be replicated!) I don't notice much difference after enabling rsync and dropping down the appropriate conf file.
