### ISSUE TITLE
Powercut procedure

### ISSUE THREAD

**Issue by hughsaunders** [rcbops/ansible-lxc-rpc#591]
Hey Doc team,
I thought we should probably have instructions for actions necessary to restore a cluster after a power outage/shutdown of all nodes. This procedure is not necessary for a rolling reboot.

These are the actions I needed to restore my sat6 lab cluster after a recent power failure: 

```
ansible-playbook -e@/root/rpc_deploy/user_variables.yml playbooks/infrastructure/rabbit-startup.yml
ansible-playbook -e@/root/rpc_deploy/user_variables.yml playbooks/infrastructure/galera-startup.yml
```

The openstack services started without intervention.

I considered adding these actions to a startup script on one of the controllers but that may be dangerous if it runs before all controllers are up.

**Comment by cloudnull** [comment]
Adding @klevenstein, @Loquacity to this issue for review and delegation.
