### ISSUE TITLE
Horizon should use the same SECRET_KEY and SSL key/cert across containers

### ISSUE THREAD

**Issue by mattt416** [rcbops/ansible-lxc-rpc#62]
Currently we generate a different SECRET_KEY and SSL key/cert per horizon container -- we should probably change this so that all containers use the same SECRET_KEY value and SSL key/cert.

**Comment by cloudnull** [comment]
This is fixed in the pending CDC PR https://github.com/rcbops/ansible-lxc-rpc/pull/51. The horizon role needed requiring in order to allow them to be deployed from python wheel. However that PR is a wip and blocked on the frozen repo being operational for apt packages.
