### ISSUE TITLE
ansible lxc module

### ISSUE THREAD

**Issue by tverlaan** [rcbops/ansible-lxc-rpc#637]
Hi, I see you are using an ansible lxc module which I haven't seen elsewhere. Have you considered submitting it to ansible-modules-extras (https://github.com/ansible/ansible-modules-extras)? Or maybe put it in a separate repository so people can clone just your ansible modules (or a set of them).
If not, are you ok with me submitting it to ansible and making it into a separate repository?

Thanks!

**Comment by cloudnull** [comment]
We do have a proposal upstream for the lxc module however we need to do some refactoring on the module and resubmit it to the new modules repo. This is the original module PR "https://github.com/ansible/ansible/pull/7825". I'd be happy to work with you on this if you're interested. I', almost always in the #rackspace room on freenode.

**Comment by cloudnull** [comment]
I've updated my PR to ansible-modules-extra which can be found here: "https://github.com/ansible/ansible-modules-extras/pull/123". I'll be monitoring the pull request and let you know if it gets merged.

**Comment by tverlaan** [comment]
I haven't had much time to take a look at it until now. I'm interested in working on this if that would still be necessary. I feel like we need to separate lxc container management from attaching to the container. lxc-attach is more of a connection method and it would be really useful to have native ansible in the attached container (at least that's how I think about it). Let's try and meet in the #rackspace room, I'm on CET, so it might be a little bit difficult.
