### ISSUE TITLE
Add missing Core FIlter in V9 deployment Nova Playbooks

### ISSUE THREAD

**Issue by cbruf82** [rcbops/ansible-lxc-rpc#652]
In the nova_all.yml file:

nova_scheduler_default_filters: RetryFilter,AvailabilityZoneFilter,RamFilter,ComputeFilter,CoreFilter,ComputeCapabilitiesFilter,ImagePropertiesFilter,ServerGroupAntiAffinityFilter,ServerGroupAffinityFilter,AggregateCoreFilter

**Comment by odyssey4me** [comment]
We could, of course, add every scheduler filter into the config - thus providing the capability of any existing filter/scheduler hint to be used without further customisation. That would probably result in a bit of extra load on the DB and scheduler server though. Thoughts?

**Comment by cloudnull** [comment]
@cbruf82 while the filter was not set in the default config you can override it to be whatever you'd like. Simply set the variable **nova_scheduler_default_filters** as the comma separated list of filters you want in the ``/etc/rpc_deploy/user_variables.yml*\* file and then (re)run the nova-scheduler plays to update your configs.

Default filters set for v9.0.x: "https://github.com/rcbops/ansible-lxc-rpc/blob/1bbea028674a2b5e0278232cb74e7047f4f60c4d/rpc_deployment/inventory/group_vars/nova_all.yml#L81"
