### ISSUE TITLE
The container build/setup process is slow and clunky

### ISSUE THREAD

**Issue by cloudnull** [rcbops/ansible-lxc-rpc#666]
The container build process is very slow while each host is setup in parallel the containers are built in serial per host. When there are >= 20 containers on a given infrastructure host it can take more than 20 minutes to build and setup all the required containers. To improve this process we should use host delegation where appropriate.

**Comment by odyssey4me** [comment]
Related: https://github.com/rcbops/ansible-lxc-rpc/issues/658
