### ISSUE TITLE
Cinder.conf Template Errors

### ISSUE THREAD

**Issue by jcannava** [rcbops/ansible-lxc-rpc#8]
There is an error when writing the backend sections. Also, the enabled_backends value doesn't seem right. It is using the key instead of the value from rpc_user_config.yml.

Error

---

< TASK: cinder_common | Setup Cinder Config >

---

```
    \   ^__^
     \  (oo)\_______
        (__)\       )\/\
            ||----w |
            ||     ||
```

fatal: [cinder1_cinder_volumes_container-f30a3071] => {'msg': "One or more undefined variables: 'unicode object' has no attribute 'items'", 'failed': True}
fatal: [cinder1_cinder_volumes_container-f30a3071] => {'msg': 'One or more items failed.', 'failed': True, 'changed': False, 'results': [{'msg': "One or more undefined variables: 'unicode object' has no attribute 'items'", 'failed': True}]}

FATAL: all hosts have already failed -- aborting
cinder.conf Template (partial)

...
{% if cinder_backends is defined %}

enabled_backends={% for backend in cinder_backends|dictsort %}{{ backend.0 }}{% if not loop.last %},{% endif %}{% endfor %}

{% for backend_section in cinder_backends|dictsort %}
[{{ backend_section.0 }}]
{% for key, value in backend_section.1.items() %}
{{ key }}={{ value }}
{% endfor %}

{% endfor %}
{% endif %}
...
Cinder.conf Rendered (partial)

...
enabled_backends=limit_container_types
# Then it just blow up around here. See above error...

...
rpc_user_config.yml (relevant section)
# User defined Storage Hosts, this should be a required group

storage_hosts:
  cinder1:
    ip: 172.29.236.1
    # "container_vars" can be set outside of all other options as 
    # host specific optional variables.
    container_vars:
      # In this example we are defining what cinder volumes are 
      # on a given host.
      cinder_backends:
        # if the "limit_container_types" argument is set, within 
        # the top level key of the provided option the inventory
        # process will perform a string match on the container name with
        # the value found within the "limit_container_types" argument.
        # If any part of the string found within the container 
        # name the options are appended as host_vars inside of inventory.
        limit_container_types: cinder_volume
        lvm:
          volume_group: cinder-volumes
          driver: cinder.volume.drivers.lvm.LVMISCSIDriver
          backend_name: LVM_iSCSI

**Comment by jacobwagner** [comment]
reopening this as i am currently seeing it in lab01

**Comment by jacobwagner** [comment]
```
TASK: [openstack_common | Laydown the example files] ************************** 
changed: [cinder2_cinder_volumes_container-51a9e18e]
changed: [cinder1_cinder_volumes_container-d13d66bb]

TASK: [openstack_openrc | Create openrc file] ********************************* 
ok: [cinder1_cinder_volumes_container-d13d66bb]
ok: [cinder2_cinder_volumes_container-51a9e18e]

TASK: [cinder_common | Setup Cinder Config] *********************************** 
fatal: [cinder2_cinder_volumes_container-51a9e18e] => {'msg': "One or more undefined variables: 'unicode object' has no attribute 'items'", 'failed': True}
fatal: [cinder2_cinder_volumes_container-51a9e18e] => {'msg': 'One or more items failed.', 'failed': True, 'changed': False, 'results': [{'msg': "One or more undefined variables: 'unicode object' has no attribute 'items'", 'failed': True}]}
fatal: [cinder1_cinder_volumes_container-d13d66bb] => {'msg': "One or more undefined variables: 'unicode object' has no attribute 'items'", 'failed': True}
fatal: [cinder1_cinder_volumes_container-d13d66bb] => {'msg': 'One or more items failed.', 'failed': True, 'changed': False, 'results': [{'msg': "One or more undefined variables: 'unicode object' has no attribute 'items'", 'failed': True}]}

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/cinder-all.retry

cinder1_cinder_volumes_container-d13d66bb : ok=62   changed=8    unreachable=1    failed=0   
cinder2_cinder_volumes_container-51a9e18e : ok=62   changed=8    unreachable=1    failed=0   
infra1_cinder_api_container-c3044bd3 : ok=53   changed=5    unreachable=0    failed=0   
infra2_cinder_api_container-7435006e : ok=37   changed=4    unreachable=0    failed=0   
infra3_cinder_api_container-c6de2580 : ok=37   changed=4    unreachable=0    failed=0 
```

**Comment by jacobwagner** [comment]
This is a previous inventory file issue, fixing will close when it is verified fixed
