### ISSUE TITLE
Glance notification mechanism

### ISSUE THREAD

**Issue by ionosphere80** [rcbops/ansible-lxc-rpc#90]
We configure the notification mechanism (notification_driver) in glance-api.conf to use a message queue. Without a consumer (typically ceilometer), this queue could become rather large.

**Comment by mattt416** [comment]
Hi @ionosphere80, we still need to move away from the template generator used for glance's config as outlined in https://github.com/rcbops/ansible-lxc-rpc/issues/29 for us to be able to disable rabbitmq notifications here.  I do believe notifications should be disabled by default but with the ability to enable if necessary.
