### ISSUE TITLE
QE LAB 02: unable to create virtual volumes

### ISSUE THREAD

**Issue by jcourtois** [rcbops/ansible-lxc-rpc#98]
In Lab 02, each of the cinder-scheduler services are complaining:

Free capacity not set: volume node info collection broken.
Failed to schedule_create_volume: No valid host was found.

https://gist.github.com/jcourtois/a096593208e9c7ba8771

May be an environment problem.  Could use dev help to debug.

**Comment by cloudnull** [comment]
This issue should be resolved when the PR #101 is merged.
